version: "2"

services:
  python-service:
    container_name: python-service
    build:
      context: python-service
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

  prometheus:
    image: prom/prometheus:v2.48.0
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
